version: '3'

services:
  dropshareapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: dropshare-docker
    container_name: dropshare-app
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_FOLDER_NAME: ${CLOUDINARY_FOLDER_NAME}
      PORT: ${PORT}

  db:
    image: mysql:5.7
    container_name: dropshare-mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/data/db
